# Use official python image as the base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python application file into the container
COPY app.py . 
COPY ext_app.py .

# Run the Python script
CMD ["python", "app.py"]

